### ISSUE TITLE
Refresh failed- Error no response within 1s 

### ISSUE THREAD

**Issue by domoarigato56** [kpsuperplane/homebridge-wiz-lan#135]
This plugin was working great till one day it wasn't.  It is failing to refresh every second. 
I've added all the lights to the config with Name, IP Address and MAC, but still no luck.

Any help is greatly appreciated!! 

Here is some of my log with the errors:

[5/26/2023, 2:10:53 PM] [WizSmarthome] Launched child bridge with PID 40605
[5/26/2023, 2:10:53 PM] Registering platform 'homebridge-wiz-lan.WizSmarthome'
[5/26/2023, 2:10:53 PM] [WizSmarthome] Loaded homebridge-wiz-lan v3.2.7 child bridge successfully
[5/26/2023, 2:10:53 PM] Loaded 4 cached accessories from cachedAccessories.0E927D8DC4B9.
[5/26/2023, 2:10:53 PM] [WizSmarthome] [Refresh] Setting up ping for every 5 seconds
[5/26/2023, 2:10:53 PM] [WizSmarthome] Loading accessory from cache: Wiz RGB Bulb 444f8e0db884
[5/26/2023, 2:10:53 PM] [WizSmarthome] Loading accessory from cache: Wiz RGB Bulb 444f8e9267bc
[5/26/2023, 2:10:53 PM] [WizSmarthome] Loading accessory from cache: Wiz RGB Bulb 444f8e0dca3c
[5/26/2023, 2:10:53 PM] [WizSmarthome] Loading accessory from cache: Wiz RGB Bulb 444f8e0e8c10
[5/26/2023, 2:10:53 PM] [WizSmarthome] [Socket] Setting up socket on 192.168.0.120:38900
[5/26/2023, 2:10:53 PM] Homebridge v1.6.1 (HAP v0.11.1) (WizSmarthome) is running on port 37578.
[5/26/2023, 2:10:53 PM] [WizSmarthome] [Discovery] Sending discovery UDP broadcast to 255.255.255.255:38899
[5/26/2023, 2:10:53 PM] [WizSmarthome] [Discovery] Sending discovery UDP broadcast to 192.168.0.169:38899
[5/26/2023, 2:10:53 PM] [WizSmarthome] [Discovery] Sending discovery UDP broadcast to 192.168.0.27:38899
[5/26/2023, 2:10:53 PM] [WizSmarthome] [Discovery] Sending discovery UDP broadcast to 192.168.0.200:38899
[5/26/2023, 2:10:53 PM] [WizSmarthome] Updating accessory: Ronan Light [formerly Wiz RGB Bulb 444f8e0dca3c]
[5/26/2023, 2:10:53 PM] [WizSmarthome] Updating accessory: Living Room Lamp [formerly Wiz RGB Bulb 444f8e9267bc]
[5/26/2023, 2:10:53 PM] [WizSmarthome] Updating accessory: Hall Light [formerly Wiz RGB Bulb 444f8e0db884]
[5/26/2023, 2:10:53 PM] [WizSmarthome] Updating accessory: Ronan Light
[5/26/2023, 2:10:53 PM] [WizSmarthome] Updating accessory: Hall Light
[5/26/2023, 2:10:53 PM] [WizSmarthome] Updating accessory: Living Room Lamp
[5/26/2023, 2:10:56 PM] [Bedroom Hub] (Bedroom Hub)INFO - Loading activities...
[5/26/2023, 2:10:58 PM] [WizSmarthome] [Refresh] Pinging 4 accessories...
[5/26/2023, 2:10:59 PM] [WizSmarthome] Error: No response within 1s
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-wiz-lan/src/accessories/WizLight/pilot.ts:156:14)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/26/2023, 2:11:03 PM] [WizSmarthome] [Refresh] Pinging 4 accessories...
[5/26/2023, 2:11:04 PM] [WizSmarthome] Error: No response within 1s
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-wiz-lan/src/accessories/WizLight/pilot.ts:156:14)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/26/2023, 2:11:06 PM] [Bedroom Hub] (Bedroom Hub)Error - Error retrieving info from hub : network timeout at: http://192.168.40.156:8088/-(28)
[5/26/2023, 2:11:08 PM] [WizSmarthome] [Refresh] Pinging 4 accessories...
[5/26/2023, 2:11:09 PM] [WizSmarthome] Error: No response within 1s
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-wiz-lan/src/accessories/WizLight/pilot.ts:156:14)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/26/2023, 2:11:11 PM] [Bedroom Hub] (Bedroom Hub)INFO - Loading activities...
[5/26/2023, 2:11:13 PM] [WizSmarthome] [Refresh] Pinging 4 accessories...
[5/26/2023, 2:11:14 PM] [WizSmarthome] Error: No response within 1s
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-wiz-lan/src/accessories/WizLight/pilot.ts:156:14)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by vorikxx** [comment]
made an account just to comment on this, i was having the same issue and it was due to pi hole, had 2 domains getting blocked. added them to whitelist and now the error is gone - lights still not acting 100% back to normal yet
