### ISSUE TITLE
Not working with HomeBridge 1.3.0 anymore

### ISSUE THREAD

**Issue by saschafuhrmann** [kpsuperplane/homebridge-wiz-lan#28]
After upgrading HomeBridge to 1.3.0 the plugin is not working anymore

`[22/02/2021, 10:36:52] [homebridge-wiz-lan] This plugin threw an error from the characteristic 'Model': Error: [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory. Ignoring new value.
    at Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1991:38)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1457:21)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:632:24)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2127:22)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27) See https://git.io/JtMGR for more info.`

**Comment by mitch7391** [comment]
I quick suggestion might be to try the new Homebridge beta (`v1.3.1-beta.5`) as I think Oznu has done some work to fix how Homebridge handles some of these errors. Homebridge `v1.3.x` did not break my `homebridge-wiz-lan` but it is throwing a number of warnings.

**Comment by saschafuhrmann** [comment]
Yes 1.3.1 is just released and throws only warnings every ~4 seconds now

**Comment by ppapajohn** [comment]
Hi all, 
after upgrading to 1.3.1, this plugin throws many warnings like the below: 

[2/24/2021, 9:27:38 AM] [homebridge-wiz-lan] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[2/24/2021, 9:27:38 AM] [homebridge-wiz-lan] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

Moreover, when I hide an accessory, this still appears in the Home App. 

Any help would be much appreciated.

**Comment by kpsuperplane** [comment]
Please try updating to the latest version 3.0.0 :)

**Comment by ppapajohn** [comment]
thanks @kpsuperplane, much appreciate your response. Deleted the plugin, removed the config as well, but the warning still appears. 
[2/26/2021, 2:26:40 AM] [homebridge-wiz-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.

Is there anything I am missing? If there is any info I could provide to you and the community for debugging this please let me know. 

Thanks in advance! :)
